[WIP] CI - CYG: fix EOL of called script

diff --git a/.github/workflows/codeql-analysis.yml b/.github/workflows/codeql-analysis.yml
--- a/.github/workflows/codeql-analysis.yml
+++ b/.github/workflows/codeql-analysis.yml
@@ -115,10 +115,11 @@ jobs:
             # generate batch file for CYGWIN shell 'cyg'
             pushd "$RUNNER_TEMP"
             mkdir -p cygwin
-            echo > cygwin/cyg.CMD '::@ECHO OFF'
+            echo > cygwin/cyg.CMD '@IF DEFINED CYG_DEBUG ECHO OFF'
             echo >>cygwin/cyg.CMD 'SETLOCAL'
             echo >>cygwin/cyg.CMD 'SET SCRIPT=%1'
-            echo >>cygwin/cyg.CMD "${CHO_TOOLS_DIR}\\cygwin\\bin\\bash --noprofile --norc -e -o pipefail -c 'cd \"%CD:\\=/%\"; %SCRIPT:\\=/%'"
+            echo >>cygwin/cyg.CMD 'SET SCRIPT=%SCRIPT:\\=/%'
+            echo >>cygwin/cyg.CMD "${CHO_TOOLS_DIR}\\cygwin\\bin\\bash --noprofile --norc -e -o pipefail -c 'cd \"%CD:\\=/%\"; dos2unix %SCRIPT%; %SCRIPT%'"
             echo 'Show cyg.CMD'
             cat cygwin/cyg.CMD
             popd
