[WIP] CI - fix cyg.cmd

diff --git a/.github/workflows/codeql-analysis.yml b/.github/workflows/codeql-analysis.yml
--- a/.github/workflows/codeql-analysis.yml
+++ b/.github/workflows/codeql-analysis.yml
@@ -38,9 +38,9 @@ jobs:
         # https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#changing-the-languages-that-are-analyzed
         sys:
           #- { system: ubuntu, os: ubuntu-latest , shell: bash }
-          - { system: macos , os: macos-latest  , shell: bash }
+          #- { system: macos , os: macos-latest  , shell: bash }
           - { system: cygwin, os: windows-latest, shell: 'cyg   {0}' }
-          - { system: msys2 , os: windows-latest, shell: 'msys2 {0}' }
+          #- { system: msys2 , os: windows-latest, shell: 'msys2 {0}' }
 
     defaults:
       run:
@@ -115,9 +115,10 @@ jobs:
             # generate batch file for CYGWIN shell 'cyg'
             pushd "$RUNNER_TEMP"
             mkdir -p cygwin
-            echo > cygwin/cyg.CMD '@ECHO OFF'
+            echo > cygwin/cyg.CMD '::@ECHO OFF'
             echo >>cygwin/cyg.CMD 'SETLOCAL'
-            echo >>cygwin/cyg.CMD "${CHO_TOOLS_DIR}\\cygwin\\bin\\bash --noprofile --norc -e -o pipefail -c 'cd \"\$(cygpath '%CD:\\=/%')\"; %*'"
+            echo >>cygwin/cyg.CMD 'SET SCRIPT=%1'
+            echo >>cygwin/cyg.CMD "${CHO_TOOLS_DIR}\\cygwin\\bin\\bash --noprofile --norc -e -o pipefail -c 'cd \"%CD:\\=/%\"; %SCRIPT:\\=/%'"
             echo 'Show cyg.CMD'
             cat cygwin/cyg.CMD
             popd
